#!/bin/bash
####################################
#
# Backup to NFS mount script.
#
####################################

# What to backup. 
# restore_files="/tmp/backup/*"

# Where to backup to.
# dest="/tmp/restore/"

# Create archive filename.
# day=$(date +%A)
# hostname=$(hostname -s)
# archive_file="BackUp-$(date +%d-%m-%Y_%H-%M-%S).tgz"

# Print start status message.
# echo "Backing up $restore_files to $dest/$archive_file"
# date
# echo

# Backup the files using tar.
# tar czf $dest/$archive_file $restore_files

# Print end status message.
echo
echo "Sending Backup to server"
date

#scp /tmp/backup/* ws@192.168.200.151:/tmp/backup
scp ws@192.168.200.151:/tmp/backup/* /tmp/restore


# Print sending status message.
echo
echo "Backup restore"
cd /tmp/restore/
sudo tar -zxvf /tmp/restore/backup-*
sudo cp -rf /tmp/restore/var/www/* /var/www/

# Print sending status message.
echo
echo "Backup restored"
date

# Print sending status message.
echo
echo "Clean Up"
sudo rm -r /tmp/restore/backup-*
sudo rm -r /tmp/restore/var/

# Long listing of files in $dest to check file sizes.
ls -lh $dest
